#!/usr/bin/env bash
set -euo pipefail

SCRIPT_VERSION="1.1.0"
BACKUP_DIR="/root/tunnel-secure-backups"

red() { printf '\033[31m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
blue() { printf '\033[34m%s\033[0m\n' "$*"; }

need_root() {
  if [[ $EUID -ne 0 ]]; then
    red "این اسکریپت باید با دسترسی root اجرا شود."
    echo "دستور پیشنهادی: sudo bash $0"
    exit 1
  fi
}

ask() {
  local prompt="$1"
  local default="${2:-}"
  local answer
  if [[ -n "$default" ]]; then
    read -r -p "$prompt [$default]: " answer
    answer="${answer:-$default}"
  else
    read -r -p "$prompt: " answer
  fi
  printf '%s' "$answer"
}

ask_yes_no() {
  local prompt="$1"
  local default="${2:-y}"
  local answer
  while true; do
    read -r -p "$prompt (y/n) [${default}]: " answer
    answer="${answer:-$default}"
    case "$answer" in
      y|Y) return 0 ;;
      n|N) return 1 ;;
      *) yellow "لطفاً فقط y یا n وارد کنید." ;;
    esac
  done
}

backup_file() {
  local src="$1"
  mkdir -p "$BACKUP_DIR"
  if [[ -f "$src" ]]; then
    cp -a "$src" "$BACKUP_DIR/$(basename "$src").$(date +%F-%H%M%S).bak"
  fi
}

ensure_package() {
  local pkg="$1"
  if ! dpkg -s "$pkg" >/dev/null 2>&1; then
    apt-get install -y "$pkg"
  fi
}

configure_sshd() {
  local ssh_port="$1"
  local disable_password="$2"
  local allow_users="$3"
  local ssh_dropin="/etc/ssh/sshd_config.d/00-tunnel-secure.conf"

  blue "\n[SSH] در حال تنظیمات امن SSH..."
  mkdir -p /etc/ssh/sshd_config.d
  backup_file "$ssh_dropin"

  {
    echo "# Generated by tunnel-security-wizard"
    echo "Port ${ssh_port}"
    echo "PermitRootLogin prohibit-password"
    if [[ "$disable_password" == "yes" ]]; then
      echo "PasswordAuthentication no"
      echo "KbdInteractiveAuthentication no"
      echo "ChallengeResponseAuthentication no"
    else
      echo "PasswordAuthentication yes"
    fi

    if [[ -n "$allow_users" ]]; then
      echo "AllowUsers ${allow_users}"
    fi
  } > "$ssh_dropin"

  if sshd -t; then
    systemctl restart ssh || systemctl restart sshd
    green "تنظیمات SSH با موفقیت اعمال شد."
  else
    red "پیکربندی SSH معتبر نیست. فایل را از بکاپ برگردانید: $BACKUP_DIR"
    exit 1
  fi
}

configure_fail2ban() {
  local ssh_port="$1"
  blue "\n[Fail2ban] فعال‌سازی محافظت در برابر Brute-force..."
  ensure_package fail2ban
  backup_file /etc/fail2ban/jail.local

  cat > /etc/fail2ban/jail.local <<EOC
[DEFAULT]
bantime = 1h
findtime = 10m
maxretry = 5

[sshd]
enabled = true
port = ${ssh_port}
logpath = %(sshd_log)s
backend = %(sshd_backend)s
EOC

  systemctl enable --now fail2ban
  green "Fail2ban فعال شد."
}

configure_ufw() {
  local mgmt_ip="$1"
  local ssh_port="$2"
  local tunnel_mode="$3"
  local gre_peer_ip="$4"
  local extra_ports_csv="$5"
  local gre_iface="$6"
  local enable_forwarding="$7"
  local wan_iface="$8"

  blue "\n[Firewall/UFW] تنظیم فایروال با حفظ تونل..."
  ensure_package ufw
  backup_file /etc/default/ufw
  mkdir -p "$BACKUP_DIR"
  tar -czf "$BACKUP_DIR/ufw.$(date +%F-%H%M%S).tar.gz" /etc/ufw >/dev/null 2>&1 || true

  ufw --force disable
  ufw --force reset
  ufw default deny incoming
  ufw default allow outgoing

  ufw allow from "$mgmt_ip" to any port "$ssh_port" proto tcp comment 'admin ssh'

  IFS=',' read -r -a extra_ports <<< "$extra_ports_csv"
  for p in "${extra_ports[@]}"; do
    p="$(echo "$p" | xargs)"
    [[ -z "$p" ]] && continue
    ufw allow "$p" comment 'tunnel service'
  done

  if [[ "$tunnel_mode" == "gre" || "$tunnel_mode" == "both" ]]; then
    ufw allow proto gre from "$gre_peer_ip" to any comment 'gre peer'
  fi

  if [[ "$enable_forwarding" == "yes" && -n "$gre_iface" && -n "$wan_iface" ]]; then
    sed -i 's/^DEFAULT_FORWARD_POLICY=.*/DEFAULT_FORWARD_POLICY="ACCEPT"/' /etc/default/ufw || true
    if ! grep -q '^DEFAULT_FORWARD_POLICY=' /etc/default/ufw; then
      echo 'DEFAULT_FORWARD_POLICY="ACCEPT"' >> /etc/default/ufw
    fi
    ufw route allow in on "$gre_iface" out on "$wan_iface" comment 'gre forward out'
    ufw route allow in on "$wan_iface" out on "$gre_iface" comment 'gre forward back'
  fi

  ufw --force enable
  ufw status verbose
  green "UFW فعال شد."
}

configure_sysctl_for_gre() {
  local gre_iface="$1"
  local enable_forwarding="$2"
  blue "\n[Sysctl] تنظیمات سازگار با GRE..."
  backup_file /etc/sysctl.d/99-tunnel-secure.conf

  cat > /etc/sysctl.d/99-tunnel-secure.conf <<EOC
# Generated by tunnel-security-wizard
net.ipv4.conf.all.rp_filter=2
net.ipv4.conf.default.rp_filter=2
net.ipv4.conf.${gre_iface}.rp_filter=0
net.ipv4.icmp_echo_ignore_broadcasts=1
net.ipv4.conf.all.accept_redirects=0
net.ipv4.conf.default.accept_redirects=0
net.ipv4.conf.all.send_redirects=0
net.ipv4.conf.default.send_redirects=0
EOC

  if [[ "$enable_forwarding" == "yes" ]]; then
    echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.d/99-tunnel-secure.conf
  fi

  sysctl --system >/dev/null
  green "تنظیمات sysctl اعمال شد."
}

main() {
  need_root

  blue "============================================"
  blue " Tunnel Security Wizard v${SCRIPT_VERSION}"
  blue "============================================"
  yellow "این ابزار برای سرورهایی است که از ssh-tunnel یا gre-4 استفاده می‌کنند."
  yellow "قبل از اعمال نهایی، بهتر است یک دسترسی کنسول/پنل اضطراری داشته باشید."

  if ! ask_yes_no "ادامه می‌دهید؟" "y"; then
    echo "خروج..."
    exit 0
  fi

  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y >/dev/null

  mgmt_ip="$(ask 'IP ثابت خودتان برای مدیریت (مثال: 1.2.3.4)')"
  ssh_port="$(ask 'پورت SSH فعلی سرور' '22')"

  tunnel_mode_choice="$(ask 'نوع تونل شما چیست؟ (1=ssh-tunnel , 2=gre-4 , 3=هر دو)' '3')"
  tunnel_mode="both"
  gre_peer_ip=""
  gre_iface="gre1"
  enable_forwarding="no"
  wan_iface=""

  case "$tunnel_mode_choice" in
    1) tunnel_mode="ssh" ;;
    2) tunnel_mode="gre" ;;
    3) tunnel_mode="both" ;;
    *) yellow "گزینه نامعتبر؛ حالت پیش‌فرض: هر دو" ;;
  esac

  extra_ports_csv=""
  if [[ "$tunnel_mode" == "ssh" || "$tunnel_mode" == "both" ]]; then
    extra_ports_csv="$(ask 'پورت(های) سرویس تونل SSH را با کاما وارد کنید (مثال: 443/tcp,80/tcp)' '')"
  fi

  if [[ "$tunnel_mode" == "gre" || "$tunnel_mode" == "both" ]]; then
    gre_peer_ip="$(ask 'IP سرور Peer در GRE (سمت مقابل تونل)')"
    gre_iface="$(ask 'نام اینترفیس GRE (مثال: gre1)' 'gre1')"
    if ask_yes_no "آیا GRE شما برای عبور ترافیک/Forwarding استفاده می‌شود؟" "n"; then
      enable_forwarding="yes"
      wan_iface="$(ask 'نام اینترفیس اینترنت سرور (مثال: eth0)')"
    fi
  fi

  disable_password="no"
  if ask_yes_no "می‌خواهید لاگین پسوردی SSH غیرفعال شود؟ (فقط اگر کلید SSH دارید y بزنید)" "n"; then
    disable_password="yes"
  fi

  allow_users=""
  if ask_yes_no "می‌خواهید فقط یک/چند کاربر خاص اجازه SSH داشته باشند؟" "n"; then
    allow_users="$(ask 'نام کاربر(ها) با فاصله (مثال: admin deploy)')"
  fi

  if ask_yes_no "آیا تنظیمات SSH اعمال شود؟" "y"; then
    configure_sshd "$ssh_port" "$disable_password" "$allow_users"
  fi

  if ask_yes_no "آیا Fail2ban نصب و فعال شود؟" "y"; then
    configure_fail2ban "$ssh_port"
  fi

  if [[ "$tunnel_mode" == "gre" || "$tunnel_mode" == "both" ]]; then
    if ask_yes_no "آیا sysctl سازگار با GRE اعمال شود؟" "y"; then
      configure_sysctl_for_gre "$gre_iface" "$enable_forwarding"
    fi
  fi

  if ask_yes_no "آیا فایروال UFW تنظیم و فعال شود؟" "y"; then
    configure_ufw "$mgmt_ip" "$ssh_port" "$tunnel_mode" "$gre_peer_ip" "$extra_ports_csv" "$gre_iface" "$enable_forwarding" "$wan_iface"
  fi

  green "\n✅ تمام شد. بکاپ‌ها در مسیر $BACKUP_DIR ذخیره شده‌اند."
  yellow "پیشنهاد: یک سشن SSH جدید باز کنید و اتصال را تست کنید، سپس سشن فعلی را ببندید."
}

main "$@"
