#!/usr/bin/env bash
set -euo pipefail

BACKUP_DIR="/root/tunnel-secure-backups"
SSH_DROPIN="/etc/ssh/sshd_config.d/00-tunnel-secure.conf"

red() { printf '\033[31m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
blue() { printf '\033[34m%s\033[0m\n' "$*"; }

need_root() {
  if [[ $EUID -ne 0 ]]; then
    red "This script must be run as root."
    exit 1
  fi
}

validate_port() {
  local port="$1"
  [[ "$port" =~ ^[0-9]+$ ]] || return 1
  (( port >= 1 && port <= 65535 ))
}

usage() {
  cat <<USAGE
Usage:
  sudo bash scripts/tunnel-security-emergency-ssh-recover.sh [--port 22]

What it does:
  1) Backs up current SSH/UFW config to $BACKUP_DIR
  2) Writes a minimal safe SSH drop-in (Port + PermitRootLogin yes + PasswordAuthentication yes)
  3) Validates sshd config and restarts ssh service
  4) Opens SSH port in UFW globally to restore access quickly

Use this ONLY from emergency console (VNC/KVM/provider console).
USAGE
}

backup_file() {
  local src="$1"
  mkdir -p "$BACKUP_DIR"
  if [[ -f "$src" ]]; then
    cp -a "$src" "$BACKUP_DIR/$(basename "$src").$(date +%F-%H%M%S).bak"
  fi
}

main() {
  need_root

  local ssh_port="22"

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --port)
        ssh_port="${2:-}"
        shift 2
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        red "Unknown argument: $1"
        usage
        exit 1
        ;;
    esac
  done

  if ! validate_port "$ssh_port"; then
    red "Invalid port: $ssh_port"
    exit 1
  fi

  blue "[1/4] Backup current config"
  backup_file "$SSH_DROPIN"
  backup_file /etc/default/ufw
  if [[ -d /etc/ufw ]]; then
    tar -czf "$BACKUP_DIR/ufw.emergency.$(date +%F-%H%M%S).tar.gz" /etc/ufw >/dev/null 2>&1 || true
  fi

  blue "[2/4] Write emergency SSH drop-in"
  mkdir -p /etc/ssh/sshd_config.d
  cat > "$SSH_DROPIN" <<EOC
# Generated by tunnel-security emergency recovery
Port ${ssh_port}
PermitRootLogin yes
PasswordAuthentication yes
KbdInteractiveAuthentication yes
ChallengeResponseAuthentication yes
UsePAM yes
EOC

  blue "[3/4] Validate and restart SSH"
  if ! sshd -t; then
    red "sshd config validation failed."
    exit 1
  fi
  systemctl restart ssh || systemctl restart sshd

  blue "[4/4] Open SSH in UFW (global allow)"
  if command -v ufw >/dev/null 2>&1; then
    ufw --force disable || true
    ufw --force reset || true
    ufw default deny incoming || true
    ufw default allow outgoing || true
    ufw allow "$ssh_port"/tcp comment 'emergency ssh recover' || true
    ufw --force enable || true
    ufw status verbose || true
  else
    yellow "ufw not installed; skipped firewall step."
  fi

  green "Emergency SSH recovery completed."
  yellow "Now test SSH login from a new terminal before closing console access."
  yellow "After login, immediately run tunnel-security-wizard again to harden safely."
}

main "$@"
