#!/usr/bin/env bash
set -euo pipefail

SCRIPT_VERSION="1.2.1"
BACKUP_DIR="/root/tunnel-secure-backups"

red() { printf '\033[31m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
blue() { printf '\033[34m%s\033[0m\n' "$*"; }

need_root() {
  if [[ $EUID -ne 0 ]]; then
    red "This script must be run as root."
    echo "Suggested command: sudo bash $0"
    exit 1
  fi
}

validate_ipv4_or_cidr() {
  local ip="$1"
  if [[ "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}(/[0-9]{1,2})?$ ]]; then
    return 0
  fi
  return 1
}

validate_port() {
  local port="$1"
  [[ "$port" =~ ^[0-9]+$ ]] || return 1
  (( port >= 1 && port <= 65535 ))
}

validate_iface_exists() {
  local iface="$1"
  ip link show "$iface" >/dev/null 2>&1
}

ask() {
  local prompt="$1"
  local default="${2:-}"
  local answer
  if [[ -n "$default" ]]; then
    read -r -p "$prompt [$default]: " answer
    answer="${answer:-$default}"
  else
    read -r -p "$prompt: " answer
  fi
  printf '%s' "$answer"
}

ask_yes_no() {
  local prompt="$1"
  local default="${2:-y}"
  local answer
  while true; do
    read -r -p "$prompt (y/n) [${default}]: " answer
    answer="${answer:-$default}"
    case "$answer" in
      y|Y) return 0 ;;
      n|N) return 1 ;;
      *) yellow "Please enter only y or n." ;;
    esac
  done
}

backup_file() {
  local src="$1"
  mkdir -p "$BACKUP_DIR"
  if [[ -f "$src" ]]; then
    cp -a "$src" "$BACKUP_DIR/$(basename "$src").$(date +%F-%H%M%S).bak"
  fi
}

ensure_package() {
  local pkg="$1"
  if ! dpkg -s "$pkg" >/dev/null 2>&1; then
    apt-get install -y "$pkg"
  fi
}

configure_sshd() {
  local ssh_port="$1"
  local disable_password="$2"
  local allow_users="$3"
  local ssh_dropin="/etc/ssh/sshd_config.d/00-tunnel-secure.conf"

  blue "\n[SSH] Applying secure SSH settings..."
  mkdir -p /etc/ssh/sshd_config.d
  backup_file "$ssh_dropin"

  {
    echo "# Generated by tunnel-security-wizard"
    echo "Port ${ssh_port}"
    echo "PermitRootLogin prohibit-password"
    if [[ "$disable_password" == "yes" ]]; then
      echo "PasswordAuthentication no"
      echo "KbdInteractiveAuthentication no"
      echo "ChallengeResponseAuthentication no"
    else
      echo "PasswordAuthentication yes"
    fi

    if [[ -n "$allow_users" ]]; then
      echo "AllowUsers ${allow_users}"
    fi
  } > "$ssh_dropin"

  if sshd -t; then
    systemctl restart ssh || systemctl restart sshd
    green "SSH settings applied successfully."
  else
    red "Invalid SSH config detected. Attempting rollback..."
    rm -f "$ssh_dropin"
    latest_backup="$(ls -1t "$BACKUP_DIR"/00-tunnel-secure.conf.*.bak 2>/dev/null | head -n1 || true)"
    if [[ -n "${latest_backup:-}" ]]; then
      cp -a "$latest_backup" "$ssh_dropin"
    fi
    exit 1
  fi
}

configure_fail2ban() {
  local ssh_port="$1"
  blue "\n[Fail2ban] Enabling brute-force protection..."
  ensure_package fail2ban
  backup_file /etc/fail2ban/jail.local

  cat > /etc/fail2ban/jail.local <<EOC
[DEFAULT]
bantime = 1h
findtime = 10m
maxretry = 5

[sshd]
enabled = true
port = ${ssh_port}
logpath = %(sshd_log)s
backend = %(sshd_backend)s
EOC

  systemctl enable --now fail2ban
  green "Fail2ban enabled successfully."
}

configure_ufw() {
  local mgmt_ip="$1"
  local ssh_port="$2"
  local tunnel_mode="$3"
  local gre_peer_ip="$4"
  local extra_ports_csv="$5"
  local gre_iface="$6"
  local enable_forwarding="$7"
  local wan_iface="$8"

  blue "\n[Firewall/UFW] Applying firewall rules while preserving tunnel access..."
  ensure_package ufw
  backup_file /etc/default/ufw
  mkdir -p "$BACKUP_DIR"
  tar -czf "$BACKUP_DIR/ufw.$(date +%F-%H%M%S).tar.gz" /etc/ufw >/dev/null 2>&1 || true

  ufw --force disable
  ufw --force reset
  ufw default deny incoming
  ufw default allow outgoing

  ufw allow from "$mgmt_ip" to any port "$ssh_port" proto tcp comment 'admin ssh'

  IFS=',' read -r -a extra_ports <<< "$extra_ports_csv"
  for p in "${extra_ports[@]}"; do
    p="$(echo "$p" | xargs)"
    [[ -z "$p" ]] && continue
    ufw allow "$p" comment 'tunnel service'
  done

  if [[ "$tunnel_mode" == "gre" || "$tunnel_mode" == "both" ]]; then
    ufw allow proto gre from "$gre_peer_ip" to any comment 'gre peer'
  fi

  if [[ "$enable_forwarding" == "yes" && -n "$gre_iface" && -n "$wan_iface" ]]; then
    sed -i 's/^DEFAULT_FORWARD_POLICY=.*/DEFAULT_FORWARD_POLICY="ACCEPT"/' /etc/default/ufw || true
    if ! grep -q '^DEFAULT_FORWARD_POLICY=' /etc/default/ufw; then
      echo 'DEFAULT_FORWARD_POLICY="ACCEPT"' >> /etc/default/ufw
    fi
    ufw route allow in on "$gre_iface" out on "$wan_iface" comment 'gre forward out'
    ufw route allow in on "$wan_iface" out on "$gre_iface" comment 'gre forward back'
  fi

  ufw --force enable
  ufw status verbose
  green "UFW enabled successfully."
}

configure_sysctl_for_gre() {
  local gre_iface="$1"
  local enable_forwarding="$2"
  blue "\n[Sysctl] Applying GRE-compatible kernel settings..."
  backup_file /etc/sysctl.d/99-tunnel-secure.conf

  cat > /etc/sysctl.d/99-tunnel-secure.conf <<EOC
# Generated by tunnel-security-wizard
net.ipv4.conf.all.rp_filter=2
net.ipv4.conf.default.rp_filter=2
net.ipv4.conf.${gre_iface}.rp_filter=0
net.ipv4.icmp_echo_ignore_broadcasts=1
net.ipv4.conf.all.accept_redirects=0
net.ipv4.conf.default.accept_redirects=0
net.ipv4.conf.all.send_redirects=0
net.ipv4.conf.default.send_redirects=0
EOC

  if [[ "$enable_forwarding" == "yes" ]]; then
    echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.d/99-tunnel-secure.conf
  fi

  sysctl --system >/dev/null
  green "Sysctl settings applied successfully."
}

main() {
  need_root

  blue "============================================"
  blue " Tunnel Security Wizard v${SCRIPT_VERSION}"
  blue "============================================"
  yellow "This wizard is intended for servers using ssh-tunnel or gre-4."
  yellow "Before applying final changes, make sure you have emergency console access."

  if ! ask_yes_no "Do you want to continue?" "y"; then
    echo "Exit."
    exit 0
  fi

  export DEBIAN_FRONTEND=noninteractive
  apt-get update >/dev/null

  mgmt_ip="$(ask 'Management IP (example: 1.2.3.4 or 1.2.3.4/32)')"
  if ! validate_ipv4_or_cidr "$mgmt_ip"; then
    red "Invalid management IP format."
    exit 1
  fi

  ssh_port="$(ask 'Current SSH port' '22')"
  if ! validate_port "$ssh_port"; then
    red "Invalid SSH port. Must be a number between 1 and 65535."
    exit 1
  fi

  tunnel_mode_choice="$(ask 'Tunnel mode? (1=ssh-tunnel , 2=gre-4 , 3=both)' '3')"
  tunnel_mode="both"
  gre_peer_ip=""
  gre_iface="gre1"
  enable_forwarding="no"
  wan_iface=""

  case "$tunnel_mode_choice" in
    1) tunnel_mode="ssh" ;;
    2) tunnel_mode="gre" ;;
    3) tunnel_mode="both" ;;
    *) yellow "Invalid option; defaulting to both." ;;
  esac

  extra_ports_csv=""
  if [[ "$tunnel_mode" == "ssh" || "$tunnel_mode" == "both" ]]; then
    extra_ports_csv="$(ask 'SSH tunnel service port(s), comma-separated (example: 443/tcp,80/tcp)' '')"
  fi

  if [[ "$tunnel_mode" == "gre" || "$tunnel_mode" == "both" ]]; then
    gre_peer_ip="$(ask 'GRE peer IP (remote tunnel endpoint)')"
    if ! validate_ipv4_or_cidr "$gre_peer_ip"; then
      red "Invalid GRE peer IP format."
      exit 1
    fi

    gre_iface="$(ask 'GRE interface name (example: gre1)' 'gre1')"

    if ask_yes_no "Is GRE used for traffic forwarding/routing?" "n"; then
      enable_forwarding="yes"
      wan_iface="$(ask 'WAN interface name (example: eth0)')"
      if ! validate_iface_exists "$wan_iface"; then
        red "WAN interface not found: $wan_iface"
        echo "Use this command to list interfaces: ip -br link"
        exit 1
      fi
    fi
  fi

  disable_password="no"
  if ask_yes_no "Disable SSH password login? (answer y only if SSH key auth is ready)" "n"; then
    disable_password="yes"
  fi

  allow_users=""
  if ask_yes_no "Limit SSH access to specific user(s)?" "n"; then
    allow_users="$(ask 'Username(s) separated by spaces (example: admin deploy)')"
  fi

  if ask_yes_no "Apply SSH hardening settings now?" "y"; then
    configure_sshd "$ssh_port" "$disable_password" "$allow_users"
  fi

  if ask_yes_no "Install and enable Fail2ban now?" "y"; then
    configure_fail2ban "$ssh_port"
  fi

  if [[ "$tunnel_mode" == "gre" || "$tunnel_mode" == "both" ]]; then
    if ask_yes_no "Apply GRE-compatible sysctl settings now?" "y"; then
      configure_sysctl_for_gre "$gre_iface" "$enable_forwarding"
    fi
  fi

  if ask_yes_no "Apply and enable UFW firewall now?" "y"; then
    configure_ufw "$mgmt_ip" "$ssh_port" "$tunnel_mode" "$gre_peer_ip" "$extra_ports_csv" "$gre_iface" "$enable_forwarding" "$wan_iface"
  fi

  green "\nDone. Backups were saved in: $BACKUP_DIR"
  yellow "Recommendation: open a new SSH session and verify connectivity before closing this one."
}

main "$@"
